create project structure
oleksandrstarov/svelte pull request #3
Opened 2024-09-26 15:28 UTC by Avareco

2024-09-26 16:54 UTC, Aleshchenk0 requested changes

2024-09-26 16:54 UTC, Aleshchenk0 commented on package.json
> +    "@types/eslint": "^9.6.0",
I think now types are redundant due the typescript was deleted. Correct me if it uses for whatever.

2024-09-26 16:54 UTC, Aleshchenk0 commented on src/App.svelte
> +    import {Badge} from "flowbite-svelte";
There are some moments when we have inconsistency in code. For example, single quotes and double quotes, some issues with tabulation so, run script `npm run format`, please. It'll fix it.

2024-09-26 17:00 UTC, Avareco commented on package.json
> +    "@types/eslint": "^9.6.0",
good catch, I will fix

2024-09-26 17:02 UTC, Avareco commented
@Aleshchenk0 , @oleksandrstarov , I propose use pnpm instead of npm, as pnpm is faster, what do you think about it?

2024-09-26 17:03 UTC, Avareco commented on src/App.svelte
> +    import {Badge} from "flowbite-svelte";
I'll add this script and corresponding rules

2024-09-26 19:49 UTC, oleksandrstarov commented
@Avareco basically package management performance is not really a problem yet and probably wont be an issue at all, but if you really want to switch to pnpm I dont see any problems with this

2024-09-26 19:52 UTC, oleksandrstarov commented
I see a good changes in direction we have discussed, nice

2024-09-26 19:53 UTC, oleksandrstarov approved these changes

2024-09-27 10:31 UTC, Aleshchenk0 approved these changes

2024-09-27 10:36 UTC, merged